spring:
  application:
    name: SKA-server

  aop:
    proxy-target-class: false

  jpa:
    open-in-view: false

    properties:
      hibernate:
        format_sql: false

  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8080
